# Generated by Django 3.1.2 on 2022-05-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20220516_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
        migrations.DeleteModel(
            name='TeacherStudent',
        ),
    ]
